[phases.setup]
nixPkgs = ["nodejs", "chromium"]

[phases.install]
cmds = [
    "npm install",
    "npx playwright install-deps chromium",
    "npx playwright install chromium"
]

[start]
cmd = "npm start"
